### ISSUE TITLE
Back (AppService) : Add Kubernetes service

### ISSUE THREAD

**Issue by Azkali** [Azkali/Dockeroid#3]
# Kubernetes for the win

[Github - Kubernetes](https://github.com/kubernetes/kubernetes)

## Architecture of Kubernetes Service

TBC by @GerkinDev

**Comment by Azkali** [comment]
Decided not to include Kubernetes service.
Closing #3

**Comment by GerkinDev** [comment]
Kubernetes is designed for clustering & scaling of applications. In our case, each user uses its own application on demand.
